# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://utviksbygdegard.se/"
defaultContentLanguage = "sv"
theme = "congo"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

enableGitInfo = true
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[outputs]
home = ["HTML", "RSS", "JSON"]
