# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://utviksbygdegard.se/"
defaultContentLanguage = "sv"
theme = "congo"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

enableGitInfo = true
[frontmatter]
lastmod = ['lastmod', ':fileModTime', ':default']

[outputs]
home = ["HTML", "RSS", "JSON"]
