# netlify.toml

[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.124.1"
NODE_ENV = "production"
TZ = "Europe/Stockholm"  # Set to preferred timezone

[context.production.environment]
HUGO_ENV = "production"
