# netlify.toml

[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
NODE_ENV = "production"
TZ = "UTC"               # Set to preferred timezone
HUGO_VERSION = "0.119.0"

[context.production.environment]
HUGO_ENV = "production"
