# netlify.toml

[build]
command = "hugo mod get -u && hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.128.0"
NODE_ENV = "production"
TZ = "Europe/Stockholm"  # Set to preferred timezone

[context.production.environment]
HUGO_ENV = "production"
